pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'ap-south-1'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Raja4123/Terraform.git'
                 bat 'cd Practice-1'
            }
        }
        
        stage('Init') {
            steps {
                
                bat 'cd Practice-1 && terraform init'
            }
        }

        stage('Plan') {
            steps {
                bat 'cd Practice-1 && terraform plan'
            }
        }

        stage('Apply') {
            steps {
                input "Approve to Apply?"
                bat 'cd Practice-1 && terraform apply -auto-approve'
            }
        }
    }
}
